#ifndef _ENGINEERROR_H_
#define _ENGINEERROR_H_


#define PK_NOERROR 0
#define PK_ERROR 1
#define PK_ERROR_NULLPTR 2
#define PK_COMPONENT_NULLPTR 3
#define PK_COMPONENT_CREATE_FAILED 4
#define PK_COMPONENT_EXIST 5
#define PK_COMPONENT_CANNOT_FIND 6
#define PK_LAYER_EXIST 7
#define PK_LAYER_CANNOT_FIND 8
#define PK_GAMEOBJECT_NULLPTR 9
#define PK_GAMEOBJECT_CANNOT_FIND 10
#define PK_INPUT_DEVICE_INIT_FAIL 11
#define PK_MODEL_FILE_NOT_OPENED 12
#define PK_SHADER_CREATE_FAILED 13
#define PK_ERROR_MESHFILE_OPEN 14
#define PK_MESH_CREATE_FAILED 15
#define PK_TEXTURE_CREATE_FAILED 16

// OpenGL
#define PK_WINDOW_CREATE_ERROR 100
#define PK_GLFW_INIT_FAIL 101


#endif //_ENGINEERROR_H_